language: objective-c
os: osx
osx_image: xcode9
xcode_project: Monique.xcodeproj
xcode_scheme: MoniqueCI
before_script:
- security create-keychain -p travis mac-build.keychain
- security import ./certs/apple.cer -k ~/Library/Keychains/mac-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.cer -k ~/Library/Keychains/mac-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.p12 -k ~/Library/Keychains/mac-build.keychain -P $KEY_PASSWORD
  -T /usr/bin/codesign
script:
- xcodebuild clean test -project Monique.xcodeproj -scheme MoniqueCI CODE_SIGNING_REQUIRED=NO
  CODE_SIGN_IDENTITY=""
after_script:
- security delete-keychain ios-build.keychain
after_success:
- echo "Configure Travis CI to deploy into TestFlight"
env:
  global:
    secure: LGpUv3Jb50S/ByjBZo9axsb/pBkUPhh6kGTTssosAPcAvfV37KmuW8LkAcQgwJoks5waMwg9Muz6nMzFpjFvAyD8pki+eRn8JDkKyK8KLnGBY5Ub2QSA5mmMyaatR5ckbiNJApu3gVo8VU3T7Wo57SRf+LLsX0ElxK/4fnEtlLPUQ0IWMGf//qV40hqJFMToV6pjUpB2fDbbM1bsjmsu0sxHV13LF/RkFSuFs+MyoK8sJPDR+b0FWpsS0A1HJrMWMjh9lnduuaXi5KOf344fsiZoGgiOfORXqbQ1D9w/8tZSdilbZv2lMgNoP3BV/TBQPmCPPdDMfvXpV5RBTc8apa3E4V+SSMd+uy1Si6FSu2VO0HObuHOm6mnQ25WTbbRPf5itPSfpJwEao896WVelJGcIJGwDhEPDCw6s1YxkDfYm+9k338I/J3PvL0bec561qNcUeCN9MOG6lc1PDf3OymVXa04zDcguu9PJjSGTy6uFnhkMVLZqiKeCb+NEuxqX40Sb4zsdJuYKO+6SGBGJAK6dW3MW4bPWTdUIRx2M0MUHA7xqihrgQ4R7AgETfYGK5hph/M3qnOJTq9/i5vmsUvPS15kz4VYaq+7ckDsPs7l7gPi8LOEs0/lmX3jzr0x0/jYMrXEsgdtywtLckguTxfyJU3zQF2Paj1qq/4/kr/k=
