language: objective-c
os: osx
osx_image: xcode9
env:
  - CODE_SIGNING_REQUIRED=0

xcode_project: Monique.xcodeproj
xcode_scheme: MoniqueCI

script:
  - xcodebuild clean build -project Monique.xcodeproj -scheme MoniqueCI
