language: objective-c
os: osx
osx_image: xcode9
env:
  - CODE_SIGNING_REQUIRED=NO
  - CODE_SIGN_IDENTITY=""

xcode_project: Monique.xcodeproj
xcode_scheme: MoniqueCI

script:
  - xcodebuild clean test -project Monique.xcodeproj -scheme MoniqueCI CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
