osx_image: xcode9
language: objective-c
env:
  - CODE_SIGNING_REQUIRED=NO
xcode_project: Monique.xcodeproj
xcode_scheme: MoniqueCI
script:
  - xcodebuild clean build -project Monique.xcodeproj -scheme MoniqueCI CODE_SIGNING_REQUIRED=NO
